### ISSUE TITLE
bug in scrolling "credits" display 

### ISSUE THREAD

**Issue by mkosma** [ncase/nutshell#1]
Hi Nicky!

Monty here (@mkosma). Danielle (@dstrachman) mentioned Nutshell on a call today and I had to check it out.

Minor bug discovered: the scrolling "thanks" display aborts before getting through the C's (around Cristy) and restarts the list. The behavior also occurs on the embedded page (https://ncase.me/thanks/aug2022.html?credits=1). 

(I can see the whole list if I remove `?credits=1` from the url.)

Anyway, Nutshell looks very cool ... should be super handy if I can link it into Logseq...

monty

**Comment by ChildishGiant** [comment]
I can't replicate this on Firefox but I can on Chrome v104 🤔

**Comment by ncase** [comment]
Hi sorry this took a while! I was, for some reason, only able to replicate this _once_ on Chrome, then it worked as expected since then?

I have no idea what happened, but I suspect it was because my code for the scrolling credits calculated the height of the page _once on load_. I think maybe it calculated too early, before everything loaded, hence it thought the page's height was shorter. I changed it so it just calculates the page height over and over.

Let me know if the problem was fixed (clear your cache if need be); thank you for catching this!
