### ISSUE TITLE
Close button not `<a>`

### ISSUE THREAD

**Issue by Foggalong** [ncase/nutshell#19]
This is an amazing tool, thanks for creating it! The button to close nutshells isn't showing up as a clickable link in the tool I use to avoid using a mouse for RSI reasons. The close all nutshells button also isn't showing up as a link, which means the only way to close them is to find the link which originally opened them.

![Screenshot from 2022-08-29 10-32-22](https://user-images.githubusercontent.com/5920259/187172092-12a2c806-1730-4f02-b8be-1d64b8f537e3.png)

**Comment by Foggalong** [comment]
I don't know much about HTML, but my _guess_ is it's to do with the close button being implemented as a `<div>` rather than `<a>` or `<button>` which seems to be what the others are using

**Comment by masonhfisher** [comment]
Yeah if I'm correct the `<div>` should be instead a `<a>` or a `<button>` because of accessibility reasons such as the one you showcased.
However the developer can give it the [ARIA button role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role) which makes accessibility tools treat the `<div>` as a button.
Edit: On further inspection the "close all nutshells" button seems to not be focusable on the keyboard which might be an issue, changing it to a button fixes the issue of it being not focusable however it can't be activated on the keyboard.

**Comment by ncase** [comment]
Fixed with @chriscoyier's pull request – thank you @Foggalong and @MachineThing for bringing up this important accessibility oversight! 👍  (And sincere apologies for my slowpokishness)
